<?php

/**
 * @file
 * Restrict Media library so users can only access media they created.
 */

/**
 * Implements hook_query_alter().
 */
function media_library_user_restrict_query_alter(QueryAlterableInterface $query) {
  if ($_GET['q'] == 'media/browser/list') {
    $tables = $query->getTables();
    if (isset($tables['base']) && $tables['base']['table'] == 'file_managed') {
      global $user;
      $query->condition('uid', $user->uid);
    }
  }
}
